services:
  servicio-auth:
    image: escuela5estrellas/servicio-auth:latest
    build:
      context: ./microservicios/servicio-auth
      dockerfile: Dockerfile
    container_name: servicio_auth
    environment:
      - PORT=3000
      - JWT_SECRET=supersecret_key_jwt_5_estrellas_2026
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/escuela5estrellas?schema=auth
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: postgres_escuela
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=escuela5estrellas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d escuela5estrellas"]
      interval: 10s
      timeout: 5s
      retries: 5

  servicio-estudiantes:
    image: escuela5estrellas/servicio-estudiantes:latest
    build:
      context: ./microservicios/servicio-estudiantes
      dockerfile: Dockerfile
    container_name: servicio_estudiantes
    environment:
      - PORT=3001
      - JWT_SECRET=supersecret_key_jwt_5_estrellas_2026
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/escuela5estrellas?schema=estudiantes
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
